version: "3.9"

services:

  nginx:
    image: nginx:latest
    container_name: reverse-proxy

    ports:
      - "80:80"

    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro

    networks:
      - web-network

networks:
  web-network:
    external: true