version: "3.9"

services:

  nginx:
    image: nginx:latest
    container_name: reverse-proxy

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare

    networks:
      - web-network

networks:
  web-network:
    external: true