events {}

http {

    server {
        listen 443 ssl;
        server_name jephreyes.com www.jephreyes.com;

        ssl_certificate /etc/ssl/cloudflare/cert.pem;
        ssl_certificate_key /etc/ssl/cloudflare/key.pem;

        location / {
            proxy_pass http://my-website-ui:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name mywebsiteapi.jephreyes.com;

        location / {
            proxy_pass http://my-website-api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # server {
    #     listen 80;
    #     server_name app-demo.local;
    #
    #     location / {
    #         proxy_pass http://app-demo:80;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #     }
    # }
    
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
}